"""Task configuration helpers and experiment assembly utilities."""

from continuum_sim.tasks.navigation_config import (
    MujocoNavigationConfig,
    NavigationControllerConfig,
    NavigationMissionConfig,
    NavigationMujocoConfig,
    NavigationSimulationConfig,
    NavigationVisualizationConfig,
    load_mujoco_navigation_config,
)
from continuum_sim.tasks.trajectory_tracking_config import (
    MujocoTrackingConfig,
    TrackingConfig,
    TrackingControllerConfig,
    TrackingMujocoConfig,
    TrackingSimulationConfig,
    TrackingTrajectoryConfig,
    TrackingVisualizationConfig,
    build_target_positions,
    load_mujoco_tracking_config,
    load_tracking_config,
)
from continuum_sim.tasks.dmp_trajectory import DiscreteDMP, DMPRollout, load_demonstration
from continuum_sim.tasks.engine_cleaning_path import (
    EngineCleaningPathSpec,
    EngineCleaningPlan,
    build_engine_cleaning_plan,
)
from continuum_sim.tasks.engine_navigation import (
    EngineNavigationLocalPathPlan,
    EngineNavigationLocalPathSpec,
    EngineNavigationLocalTrackingSpec,
    EngineNavigationObserverControlSpec,
    EngineNavigationPlan,
    EngineNavigationSpec,
    resolve_engine_navigation_plan,
)
from continuum_sim.tasks.navigation_mission import NavigationMissionSpec, resolve_navigation_waypoints
from continuum_sim.tasks.task_plan import (
    BaseApproachConstraint,
    ClearanceConstraint,
    TaskPhasePlan,
    TaskPlan,
)
from continuum_sim.tasks.trajectory_generation import TrajectorySpec, generate_trajectory_waypoints
from continuum_sim.tasks.wiping_path import WipingPathPlan, WipingPathSpec, build_wiping_plan
from continuum_sim.tasks.wiping_config import (
    MujocoWipingConfig,
    WipingControllerConfig,
    WipingMotionConfig,
    WipingMujocoConfig,
    WipingPath,
    WipingSceneConfig,
    WipingSimulationConfig,
    WipingToolConfig,
    WipingVisualizationConfig,
    build_raster_wiping_path,
    load_mujoco_wiping_config,
)

__all__ = [
    "MujocoNavigationConfig",
    "MujocoTrackingConfig",
    "MujocoWipingConfig",
    "DiscreteDMP",
    "DMPRollout",
    "EngineCleaningPathSpec",
    "EngineCleaningPlan",
    "EngineNavigationPlan",
    "EngineNavigationLocalPathPlan",
    "EngineNavigationLocalPathSpec",
    "EngineNavigationLocalTrackingSpec",
    "EngineNavigationObserverControlSpec",
    "EngineNavigationSpec",
    "NavigationControllerConfig",
    "NavigationMissionConfig",
    "NavigationMissionSpec",
    "NavigationMujocoConfig",
    "NavigationSimulationConfig",
    "NavigationVisualizationConfig",
    "BaseApproachConstraint",
    "ClearanceConstraint",
    "TaskPhasePlan",
    "TaskPlan",
    "TrackingConfig",
    "TrackingControllerConfig",
    "TrackingMujocoConfig",
    "TrackingSimulationConfig",
    "TrackingTrajectoryConfig",
    "TrackingVisualizationConfig",
    "WipingControllerConfig",
    "WipingMotionConfig",
    "WipingMujocoConfig",
    "WipingPath",
    "WipingSceneConfig",
    "WipingSimulationConfig",
    "WipingToolConfig",
    "WipingVisualizationConfig",
    "WipingPathPlan",
    "WipingPathSpec",
    "TrajectorySpec",
    "build_engine_cleaning_plan",
    "build_target_positions",
    "build_raster_wiping_path",
    "build_wiping_plan",
    "generate_trajectory_waypoints",
    "load_mujoco_navigation_config",
    "load_mujoco_tracking_config",
    "load_mujoco_wiping_config",
    "load_demonstration",
    "load_tracking_config",
    "resolve_navigation_waypoints",
    "resolve_engine_navigation_plan",
]
